# Generated by Django 2.0.2 on 2018-02-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField()),
                ('professor_name', models.TextField(max_length=30)),
                ('professor_email', models.EmailField(max_length=254)),
                ('class_running', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('student_name', models.TextField(max_length=30)),
                ('acknowledged', models.IntegerField(default=0)),
                ('modifier', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='student_list',
            field=models.ManyToManyField(to='app.Student'),
        ),
    ]
