# Generated by Django 2.0.2 on 2018-02-19 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='student_list',
        ),
        migrations.AddField(
            model_name='student',
            name='class_room',
            field=models.ForeignKey(default=9,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='app.ClassRoom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='hand',
            field=models.BooleanField(default=False),
        ),
    ]
